# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Composite": "00_generate_screenshot_images.ipynb",
         "df": "00_generate_screenshot_images.ipynb",
         "ax": "00_generate_screenshot_images.ipynb",
         "fig": "00_generate_screenshot_images.ipynb",
         "gs": "00_generate_screenshot_images.ipynb",
         "BoardGenerator": "00_generate_screenshot_images.ipynb",
         "SSComposite": "00_generate_screenshot_images.ipynb",
         "get_images": "00_generate_screenshot_images.ipynb",
         "train_imgs": "00_generate_screenshot_images.ipynb",
         "test_imgs": "00_generate_screenshot_images.ipynb",
         "val_imgs": "00_generate_screenshot_images.ipynb",
         "a": "00_generate_screenshot_images.ipynb",
         "b": "00_generate_screenshot_images.ipynb",
         "c": "00_generate_screenshot_images.ipynb",
         "comps": "00_generate_screenshot_images.ipynb",
         "Coord": "02-classifier.ipynb",
         "CropBox": "02-classifier.ipynb",
         "Color": "02-classifier.ipynb",
         "Piece": "02-classifier.ipynb",
         "BoardImage": "02-classifier.ipynb",
         "get_coord": "02-classifier.ipynb"}

modules = ["screenshot.py",
           "classifier.py"]

doc_url = "https://idrisr.github.io/libchess/"

git_url = "https://github.com/idrisr/libchess/tree/main/"

def custom_doc_links(name): return None
