# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://{user}.github.io/chess/"

git_url = "https://github.com/{user}/chess/tree/{branch}/"

def custom_doc_links(name): return None
